package ll1

var tests = []struct {
	input    string
	expected bool
}{
	{"X=y(y)*y;", true},
	{"accept = 2 / (2 - cos(50 + x));", true},
	{"pass = gg(1+2/3*4);", true},
	{"C = (F-32)/1.8 ;", true},
	{"bomb = x+1;", true},
	{"test = sin(a * 30 + cos(20 + 80 + k)) + aaa(60);", true},
	{"a= a*b*c*a(c);", true},
	{"mm=1*1+1+2+3*F(x)*7/(2);", true},
	{"myfunction = sk(25+2);", true},
	{"a = b/c*(d+e)-(f/g(h-2))-1.0;", true},
	{"axz=a/x*y+sin(90);", true},
	{"tid = t*i*d/10+48;", true},
	{"cal = 10 + 2 * 5;", true},
	{"ice = gg36/   11.2        ;", true},
	{"in = ((a*b) / sin(30))- 200 ;", true},
	{"mahnmoo = is(16)*8/sin(30);", true},
	{"a=2/b(3)/(4)+(9);c=(1+x/y+9)-n(2)/r((k));", true},
	{"y =(a + b) / c - d - 0;", true},
	{"mo = arctan(Z*58+157) / F(87*y/(30*23))  - 4;", true},
	{"r= 4; area = pi * pow2(r);", true},
	{"abc = a + c + b;", true},
	{" mhw = ps(4);", true},
	{"switch = lastSwtich - 5 / opcode;", true},
	{"df=234+234;", true},
	{"g=j*(u);", true},
	{"a=((b/2)+7*(c-d)-sin(30))*322;", true},
	{"papa       =papa+papa-papa*(papa(papa(papa(papa(papa))+papa(papa/papa))));    papapapapapa=papa+papa+papa;                                         ", true},
	{"varn=(thanjira + sukkree)*9;", true},
	{"I5iH4u1EK = jivvM82Mp - GXylny3Yd + OFLGjEWja * (MqHm4wzRh / P92uf7XQa);", true},
	{"a = b*b(b);", true},
	{"x=(y+z)*(y-z)*((y+z/2)/2+(1/z));", true},
	{"aabbcc = (a+b)+(a+b);", true},
	{"asd = (bd/(bdn+5))+4-((3/6)-ads);", true},
	{"a = sin(40) + 6; a = b+4;", true},
	{"i6 = 1+12;", true},
	{"a = 80 - (f * 2) + c;", true},
	{"hello = (it + me)- 19 ;", true},
	{"x = (a-5*(c/2))+sin(30);", true},
	{"ek = x + 5;", true},
	{"F = foo1 + sin(90);", true},
	{"Nk = b * 44;", true},
	{"ongnable=(ong+nable)*1;", true},
	{"Y = (u+do)/this+3;", true},
	{"sum = (a+b)*sin(45);", true},
	{"E = (2*2)/qw;", true},
	{"a = b(cc*bb)+dd;", true},
	{"test=a(a)*5;", true},
	{"eiei=haha+(haha*haha)*haha-haha(haha(haha*haha-haha+haha));", true},
	{"a = sin(30) + cos(90); b = a / 2;", true},
	{"ford = 5 * o * r * (4 / t) + 6;", true},
	{"case1Test = (5.25+3*sin(30))/2;", true},
	{"unknown = (sin(19) + 10)/cos(19/10);", true},
	{"x = aa+bb*cc/dd;", true},
	{"A =  sin(45)/2+pqr;", true},
	{"a = (a+1) + ( b * b );", true},
	{"r=(e45)/(ftr)-((((4.4))));", true},
	{"x = ((y+3)*sin(15)/9)-(zz(12));", true},
	{"ya = ((3 * t) / d) + (4 * t) /b;", true},
	{"q = p(8)/9-(m);", true},
	{"vali = (sen+(((((((((5.5*1*1*2*(((1+2/3)))))))))))))*5+1;", true},
	{"myVar = (eiei - log(12.34))/a321;", true},
	{"ku = y + 10;", true},
	{"I = wont + (send - It)  ;", true},
	{"D = 0 - it +(5*5);", true},
	{"T=T-T+T;", true},
	{"b = a*a*a*a;", true},
	{"u=pi/0;", true},
	{"ngun = 130*mood(trbl) ;", true},
	{"x = y-1 ;", true},
	{"X=(yy*y;", false},
	{"reject =  2 / (2 - cos(50 + x + (20 - 55))));", false},
	{"o0(./.PrayuthZa007./.)0o", false},
	{"(;", false},
	{"This = 15 * 401 *9 / bomb", false},
	{"test2 = ((28 - aaa) * (30 * (12 - 5))) + 50)", false},
	{"(())()())", false},
	{")", false},
	{"(2+(2+3)+(5))", false},
	{"a = b/c*(d+e)&f/g(h);", false},
	{"axz=56+44..5;", false},
	{"tid = t*/i/*+-*/d+-**;", false},
	{"cal////", false},
	{"ice..! / 8", false},
	{"in/((a+b)", false},
	{"ize / (.=) ike; = 1", false},
	{"a/b/*c+d=z//y", false},
	{"Boss = za + 69);", false},
	{"happy = freedom(30) + love*cos(37) * 2*relationship)(;", false},
	{"x+y=x+y;", false},
	{"K = ()(()(()))())(", false},
	{"(((((((((((((;", false},
	{"switch = opcode & switchMask;", false},
	{"rwrwercqctr", false},
	{"g=j*(uu;", false},
	{"G = 1+y*((3-x)/(mg)))", false},
	{"parser      =         lexer     (       tokenizer        )    +    1212312121.", false},
	{"sdd)f + w((", false},
	{"if you forget =;", false},
	{"a = b*(b)b;", false},
	{"x=((0-b)+-sqrt(b*b-4*a*c))/(2*a);", false},
	{"aabbcc= a**a++b**b++c**c++", false},
	{"asd = ((ko/(btn+5))-((3/6)-was)-4gh;", false},
	{"243w54e6drfyugtvj bm=-0-9ouiyughbn", false},
	{"5=((4+1)=(3+2))", false},
	{"5a = 2 * wink ;)", false},
	{"thailand = (****)+((country)", false},
	{"y = cos(60+pi)/2d g;", false},
	{": ) .__. ))", false},
	{"F = (((s)", false},
	{"Nk = b*44 / g", false},
	{"0ngnable=);", false},
	{"X=(())())(a-", false},
	{"a+((-b/c", false},
	{"E/ = qw/2", false},
	{"S = A  ( ) 3+444AB*^", false},
	{"x+y=5*45/", false},
	{"qjmtnuhrc=haeieientuhaeowhatthefucketnuhcroaehahau+hetnhuc++", false},
	{"a = b((c);", false},
	{"ford = 5 * o * r * 4 ^ t + 6;", false},
	{"G(x) = ((-6/-3);", false},
	{"981111n+ j+ (12+(72*34b)+ A = F-(3*po));", false},
	{"x = aabbccdd", false},
	{"A = sin(45/2+;", false},
	{"(((x+A) n + q (12+(222)) = Csin(pi))", false},
	{"r=(e45)/(f.tr)-(((4.4))));", false},
	{"x = a*-+12(()", false},
	{"(Aha*aha)+ha*ha-ha = (ha^ha)+ha(-ha)", false},
	{"q = p(a)/9-();", false},
	{"v_v/v_v -= bbabbababababababbabababababababababb;", false},
	{"asd = sin(2 + 123fds)/hello;", false},
	{"k = ))))))／人◕ ‿‿ ◕人＼(((", false},
	{"(((((((((((((((((((((", false},
	{")1+1( = )2+2(", false},
	{")T-T(", false},
	{"b*b = !(bb/(b/b);", false},
	{")-(", false},
	{"rvng = 100+30*mood(sin(trbl);", false},
	{"adsd(((((;", false},
}
